spring:
  application:
    name: sion-ai-code-master
server:
  port: 13831
  servlet:
    context-path: /api

# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.sion.sionaicodemaster.controller

knife4j:
  enable: true
  setting:
    language: zh_cn